fix(deploy/service): remove quotes as it was causing an error
The following error was being printed out
```
error: template name must be specified only once: default:
```

let's remove the quotes as they are not necessary.