test(environment): use mocket fake connection in environment test load services unit test
Without this the unit test requires a postgres instance to be running,
otherwise it fails with the error below
```log
=== Failed
=== FAIL: cmd/kas-fleet-manager/environments TestLoadServices (0.00s)
I0403 16:15:54.073440 1060307 environment.go:127] Initializing testing environment
panic: failed to connect to postgres database serviceapitests with connection string: host=localhost port=5432 user=kas_fleet_manager password='<REDACTED>' dbname=serviceapitests sslmode=disable
Error: dial tcp 127.0.0.1:5432: connect: connection refused [recovered]
	panic: failed to connect to postgres database serviceapitests with connection string: host=localhost port=5432 user=kas_fleet_manager password='<REDACTED>' dbname=serviceapitests sslmode=disable
Error: dial tcp 127.0.0.1:5432: connect: connection refused
```